export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const GET_USER = 'GET_USER';
export const GET_USERS_IN_ROOM = 'GET_USERS_IN_ROOM';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CONVERSATION_ERROR = 'CONVERSATION_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_ALERT = 'SET_ALERT';
export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const GET_CONVERSATION_MSGS = 'GET_CONVERSATION_MSGS';
export const SEND_CONVERSATION_MSGS = 'SEND_CONVERSATION_MSGS';
export const ADD_PARTICIPANTS = 'ADD_PARTICIPANTS';
export const SET_CURRENT_CONVERSATION = 'SET_CURRENT_CONVERSATION';
export const FILTER_CONVERSATION = 'FILTER_CONVERSATION';
export const CLEAR_FILTER = 'CLEAR_FILTER';




